import localFont from "next/font/local";
import "./globals.css";
import Image from "next/image";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      
        <header className="px-2 py-2 bg-primary text-white flex items-center">
          <Image
            src="/assets/icons/surabaya.png"
            width={40}
            height={40}
            alt="logo pemkot surabaya"
          />
          <div className="ml-1">
            <h1 className="inline-block font-semibold text-lg">
              Pendaftaran Antrian Online
            </h1>
            <h1 className="-mt-2 font-medium">Layanan Kesehatan Surabaya</h1>
          </div>
        </header>

        <main className="mx-4 mt-8 min-h-screen">{children}</main>

        <footer className="text-center text-sm mb-5">
          2024 @ Dinas Kesehatan Koita Surabaya
        </footer>
      </body>
    </html>
  );
}
